version: "2"
services:
  proxy:
    image: alpine
    build: ./
    networks:
      - web1
      - web2
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/vm/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /home/vm/proxy/backend-not-found.html:/var/www/html/backend-not-found.html

networks:
  web1:
    external: true
    name: web1_default

  web2:
    external: true
    name: web2_default
